# Generated by Django 3.1.1 on 2020-09-30 18:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room', models.CharField(max_length=40)),
                ('metric', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
