# Generated by Django 3.1.1 on 2020-09-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmetric',
            old_name='date',
            new_name='e_date',
        ),
    ]
