# Generated by Django 3.1.1 on 2020-09-30 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200930_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventmetric',
            old_name='e_date',
            new_name='dt',
        ),
    ]
